spring.application.name=ems-backend

spring.datasource.url=http://localhost:5432/ems
spring.datasource.password=postgres
spring.datasource.username=Adesh@2205

spring.jpa.hibernate.ddl-auto=update
server.port=8080